[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.5.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.4.0"
