name: CI
on:
  push:
    branches:
      - '!master'
jobs:
  test-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.12.6'
      - name: Downloading packages
        run: go mod download
        env:
          GO111MODULE: "on"
      - name: Test and Lint
        run: |
          go test -race -v ./...
          go vet ./...
          go fmt ./...
          git diff --name-only | grep "**.go$" | xargs git diff --exit-code --quiet --
          if [ $? -eq 0 ]; then echo "ok"; else echo "git diff error"; exit 1; fi
